apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: akkc01/akkc:v1
        ports:
        - containerPort: 80
