name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: akkc

      
    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v1
      ACR_NAME: b17g2aksregistry
      ACR_LOGIN_SERVER: b17g2aksregistry.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 2482a26b-0879-445e-b5d7-bb4aaed89e46
          tenant-id: c5a4bf24-fe14-4945-9d5b-ce2d45cd7404
          subscription-id: b398fea1-2f06-4948-924a-121d4ed265b0

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
